<?php

define( 'ITSEC_ENCRYPTION_KEY', 'SmlJR2xuVj9DczRsPCBNPllpZHNKOjRrLiYkO3M6bm9yKmMgd2UyRX1RdWA5WC9wd2FLRSF6LGczZFo9OlpaNQ==' );

define( 'WP_CACHE', true ); // Added by WP Rocket

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';
